export type Asset = {
  id: number;
  name: string;
  type: "cryptocurrency" | "stocks" | "bonds" | "commodity" | "currency";
  value: number;
  performance: number;
  apr: number;
  performanceOverTime: number[];
  [key: string]: any;
};

export const mockAssets: Asset[] = [
  {
    id: 1,
    name: "Bitcoin",
    type: "cryptocurrency",
    value: 45000,
    performance: 5,
    apr: 10,
    performanceOverTime: Array.from({ length: 365 }, (_, i) => 45000 + i * 10),
  },
  {
    id: 2,
    name: "Ethereum",
    type: "cryptocurrency",
    value: 3000,
    performance: 3,
    apr: 8,
    performanceOverTime: Array.from({ length: 365 }, (_, i) => 3000 + i * 5),
  },
  {
    id: 3,
    name: "Apple Stock",
    type: "stocks",
    value: 150,
    performance: 2,
    apr: 5,
    performanceOverTime: Array.from({ length: 365 }, (_, i) => 150 + i * 1),
  },
  {
    id: 4,
    name: "Tesla Stock",
    type: "stocks",
    value: 700,
    performance: 4,
    apr: 6,
    performanceOverTime: Array.from({ length: 365 }, (_, i) => 700 + i * 2),
  },
  {
    id: 5,
    name: "US Treasury Bond",
    type: "bonds",
    value: 1000,
    performance: 1,
    apr: 3,
    performanceOverTime: Array.from({ length: 365 }, (_, i) => 1000 + i * 0.5),
  },
  {
    id: 6,
    name: "Litecoin",
    type: "cryptocurrency",
    value: 200,
    performance: 2.5,
    apr: 7,
    performanceOverTime: Array.from({ length: 365 }, (_, i) => 200 + i * 3),
  },
  {
    id: 7,
    name: "Google Stock",
    type: "stocks",
    value: 2800,
    performance: 3.5,
    apr: 5.5,
    performanceOverTime: Array.from({ length: 365 }, (_, i) => 2800 + i * 4),
  },
  {
    id: 8,
    name: "Corporate Bond",
    type: "bonds",
    value: 500,
    performance: 1.5,
    apr: 4,
    performanceOverTime: Array.from({ length: 365 }, (_, i) => 500 + i * 0.8),
  },
  {
    id: 9,
    name: "Ripple",
    type: "cryptocurrency",
    value: 1,
    performance: 0.5,
    apr: 2,
    performanceOverTime: Array.from({ length: 365 }, (_, i) => 1 + i * 0.01),
  },
  {
    id: 10,
    name: "Amazon Stock",
    type: "stocks",
    value: 3500,
    performance: 4.5,
    apr: 6.5,
    performanceOverTime: Array.from({ length: 365 }, (_, i) => 3500 + i * 5),
  },
  {
    id: 11,
    name: "Dogecoin",
    type: "cryptocurrency",
    value: 0.1,
    performance: -1,
    apr: 0.5,
    performanceOverTime: Array.from({ length: 365 }, (_, i) => 0.1 + i * -0.01),
  },
  {
    id: 12,
    name: "Microsoft Stock",
    type: "stocks",
    value: 2500,
    performance: -2,
    apr: 4,
    performanceOverTime: Array.from({ length: 365 }, (_, i) => 2500 + i * -3),
  },
  {
    id: 13,
    name: "Ethereum Classic",
    type: "cryptocurrency",
    value: 50,
    performance: -3,
    apr: 1,
    performanceOverTime: Array.from({ length: 365 }, (_, i) => 50 + i * -0.5),
  },
  {
    id: 14,
    name: "Netflix Stock",
    type: "stocks",
    value: 500,
    performance: 2,
    apr: 4,
    performanceOverTime: Array.from({ length: 365 }, (_, i) => 500 + i * 2),
  },
  {
    id: 15,
    name: "Gold",
    type: "commodity",
    value: 1800,
    performance: 1.5,
    apr: 3,
    performanceOverTime: Array.from({ length: 365 }, (_, i) => 1800 + i * 1),
  },
  {
    id: 16,
    name: "Facebook Stock",
    type: "stocks",
    value: 350,
    performance: 3,
    apr: 5,
    performanceOverTime: Array.from({ length: 365 }, (_, i) => 350 + i * 1.5),
  },
  {
    id: 17,
    name: "Euro",
    type: "currency",
    value: 1.2,
    performance: 0.5,
    apr: 1,
    performanceOverTime: Array.from({ length: 365 }, (_, i) => 1.2 + i * 0.01),
  },

  {
    id: 19,
    name: "Intel Stock",
    type: "stocks",
    value: 60,
    performance: -1.5,
    apr: 2,
    performanceOverTime: Array.from({ length: 365 }, (_, i) => 60 + i * -0.5),
  },
  {
    id: 20,
    name: "Eurobond",
    type: "bonds",
    value: 1000,
    performance: 1,
    apr: 2.5,
    performanceOverTime: Array.from({ length: 365 }, (_, i) => 1000 + i * 0.5),
  },
  {
    id: 21,
    name: "Litecoin Cash",
    type: "cryptocurrency",
    value: 10,
    performance: -2.5,
    apr: 0,
    performanceOverTime: Array.from({ length: 365 }, (_, i) => 10 + i * -0.1),
  },
  {
    id: 22,
    name: "Silver",
    type: "commodity",
    value: 25,
    performance: 1,
    apr: 2,
    performanceOverTime: Array.from({ length: 365 }, (_, i) => 25 + i * 0.5),
  },
  {
    id: 23,
    name: "US Treasury Bond 10-Year",
    type: "bonds",
    value: 2000,
    performance: 1.5,
    apr: 2.5,
    performanceOverTime: Array.from({ length: 365 }, (_, i) => 2000 + i * 1),
  },
  {
    id: 24,
    name: "Municipal Bond",
    type: "bonds",
    value: 800,
    performance: 1,
    apr: 2,
    performanceOverTime: Array.from({ length: 365 }, (_, i) => 800 + i * 0.5),
  },
  {
    id: 25,
    name: "Corporate Bond 2",
    type: "bonds",
    value: 1200,
    performance: 1.2,
    apr: 2.2,
    performanceOverTime: Array.from({ length: 365 }, (_, i) => 1200 + i * 0.8),
  },
];
